### ISSUE TITLE
When will the next version be released，please

### ISSUE THREAD

**Issue by BinChengZhao** [sergeyklay/breadcrumbs#25]
Our project will be upgraded to php7.3, and phalcon extension will also be passively upgraded to 4.0, but there is no breadcrumbs package available, so please ask when you will update

**Comment by sergeyklay** [comment]
Good idea :) I'll try to release compatible version ASAP 👍

**Comment by 1096189368** [comment]
Thank you for your help in the development of our project. I am waiting for your good news

**Comment by BinChengZhao** [comment]
> Good idea :) I'll try to release compatible version ASAP 👍

Thank you for your help in the development of our project. I am waiting for your good news

**Comment by sergeyklay** [comment]
@1096189368 I've provided initial support of Phalcon 4.x in the `development` branch. Can you test this branch by any chance?

**Comment by BinChengZhao** [comment]
> @1096189368 I've provided initial support of Phalcon 4.x in the `development` branch. Can you test this branch by any chance?
Ok, we should apply for testing resources for testing, it is really hard for you, we will respond to the test results as soon as possible

**Comment by BinChengZhao** [comment]
> @1096189368 I've provided initial support of Phalcon 4.x in the `development` branch. Can you test this branch by any chance?
I'm really sorry that the company I belong to needs a lot at the end of the year, so the upgrade plan of the server PHP version has been disrupted, and there are no resources related to the test. I'm really sorry to bother you
